"""HANDOFF.md generator — one-time bootstrap doc for building this tool."""

import json
from pathlib import Path

from .config import DEFAULT_CONFIG
from .utils import DIM, fmt, git_branch, git_last_commit, git_remote_url, now_iso, write_doc


def write_handoff(root: Path, cfg: dict, languages: dict, line_counts: dict):
    ts = now_iso()
    docs = root / cfg["docs_dir"]

    total_files = sum(len(v) for v in languages.values())
    total_lines = sum(s["lines"] for s in line_counts.values())
    lang_list = ", ".join(f"{k.upper()} ({len(v)} files)" for k, v in languages.items() if v)

    # Top 10 largest files for context
    top_files = sorted(line_counts.items(), key=lambda x: x[1]["lines"], reverse=True)[:10]
    top_files_md = "\n".join(f"- `{f}` — {s['lines']} lines" for f, s in top_files)

    content = f"""# HANDOFF.md — repo-scan bootstrap

> **Note for agent/developer:** This document was auto-generated by `repo-scan` on {ts}.
> It is a one-time bootstrap artifact. Once the tool is built and functional,
> archive or delete this file. It is not a recurring output.

---

## Purpose

This document provides everything needed to build `repo-scan` as a
production-ready global CLI tool for this repository. The initial prototype
script (`scripts/repo_scan.py`) and per-repo config (`.repo-scan.json`) already
exist. This handoff defines the target architecture, UX, and build steps.

---

## Repo context

| Property | Value |
|----------|-------|
| Scanned at | {ts} |
| Remote | {git_remote_url(root)} |
| Branch | {git_branch(root)} |
| Last commit | {git_last_commit(root)} |
| Source files | {total_files} |
| Total lines | {total_lines:,} |
| Languages detected | {lang_list} |

### Largest files at time of scan

{top_files_md}

---

## Target architecture

### Global install

The tool should be installable globally via:

```bash
pip install -e /path/to/repo-scan
# or eventually:
pip install repo-scan
```

This exposes a `repo-scan` command on PATH. Internally it is a standard
Python package with a `pyproject.toml` entry point.

### Directory structure

```
repo-scan/               # the tool's own repo (separate from target repos)
  repo_scan/
    __init__.py
    cli.py               # argparse entry point
    scanner.py           # orchestrates the scan pipeline
    languages.py         # file detection, line counting
    graphs.py            # dep + call graph generation
    complexity.py        # radon, es-complexity wrappers
    churn.py             # git log analysis
    writers.py           # markdown report writers
    handoff.py           # HANDOFF.md generator
    config.py            # .repo-scan.json loader + defaults
    hooks.py             # git hook installer
    utils.py             # shared helpers
  pyproject.toml
  README.md
```

### Per-repo config

Each target repo may have a `.repo-scan.json` at its root:

```json
{json.dumps(DEFAULT_CONFIG, indent=2)}
```

The tool reads this on every run. If absent, all defaults apply.

### Git hook behavior

Running `repo-scan --install-hook` writes `.git/hooks/pre-commit`.
The hook:
1. Runs `repo-scan` against the repo root
2. Stages changed files under `docs/` automatically
3. Never blocks a commit — warnings only
4. Prints a brief summary of what changed

---

## docs/ output structure

All output is plain Markdown with Mermaid code blocks.
Point Obsidian at the repo root or `docs/` folder — everything renders natively.

```
docs/
  index.md                     # dashboard: overview, links, action items
  scan.json                    # machine-readable sidecar for agents
  reports/
    health.md                  # file sizes, complexity, churn alerts
    dependencies.md            # Mermaid dep graphs (TS + Python)
    calls.md                   # Mermaid call graphs (C via cflow)
  architecture/
    dependency-graph.md        # stable dep graph for Obsidian cross-linking
    overview.md                # hand-written (not generated)
    decisions/                 # ADRs (written by RADAR loop, not repo-scan)
  research/                    # populated by RADAR loop (not repo-scan)
    index.md
    sources/
```

---

## Tool dependencies

| Tool | Purpose | Install | Required? |
|------|---------|---------|-----------|
| tokei | Line counts | `brew install tokei` | No (fallback built in) |
| madge | TS dep graphs | `npm install -g madge` | No |
| radon | Python complexity | `pip install radon` | No |
| cflow | C call graphs | `brew install cflow` | No |
| git | Churn analysis | pre-installed | Yes |

All external tools are optional. The scan degrades gracefully and notes
what was skipped in the reports.

---

## Key design constraints

1. **Zero required deps beyond Python stdlib + git.** Everything else enhances.
2. **Output is always valid Markdown.** No tool should write broken Mermaid.
3. **Never block a commit.** The pre-commit hook is advisory only.
4. **Config is additive.** Unknown keys in `.repo-scan.json` are warned, not errors.
5. **Obsidian-first.** All cross-links use `[[wikilink]]` format.
6. **RADAR-ready.** The `docs/` structure is the shared knowledge base
   that RADAR reads from and writes into.
"""

    write_doc(docs / "HANDOFF.md", content, root)
    print(fmt("  → archive or delete HANDOFF.md once the tool is built", DIM))
